services:
  - type: web
    name: catalog-sheet-backend
    env: node
    plan: free
    buildCommand: npm run build:backend
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: FRONTEND_URL
        value: https://alnortegrow-catalog.vercel.app 